version: "3.9"
services: 
    redmine:
        image: redmine:4.2.1
        container_name: redmine_app
        restart: always
        ports: 
            - "8005:3000"
        environment: 
            REDMINE_DB_MYSQL: ${REDMINE_DB_MYSQL}
            REDMINE_DB_PASSWORD: ${REDMINE_DB_PASSWORD}
            REDMINE_DB_DATABASE: ${REDMINE_DB_DATABASE}
            REDMINE_SECRET_KEY_BASE: supersecretkey
            TZ: ${TZ}
        networks: 
            - redmine_net
    db:
        image: mariadb:10.6.3-focal
        container_name: ${REDMINE_DB_MYSQL}
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: ${REDMINE_DB_PASSWORD}
            MYSQL_DATABASE: ${REDMINE_DB_DATABASE}
            TZ: ${TZ}
        networks: 
            - redmine_net
networks: 
    redmine_net:
        driver: bridge
